from flaskr.models.actors import actors
from flaskr.models.content_actor import content_actor
from flaskr.models.content_director import content_director
from flaskr.models.content_genre import content_genre
from flaskr.models.contents import contents
from flaskr.models.directors import directors
from flaskr.models.genres import genres
from flaskr.models.ott_infos import ott_infos
from flaskr.models.user_actors import user_actors
from flaskr.models.user_contents import user_contents
from flaskr.models.user_directors import user_directors
from flaskr.models.users import users
